name: Test and Auto-merge

on:
  merge_request:
    branches: [ main ]  # main 브랜치로의 MR에 대해 실행
  pull_request:
    branches: [ main ]  # main 브랜치로의 PR에 대해 실행

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 프로젝트에 맞는 Node.js 버전을 사용하세요

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Auto-merge
        if: success()
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"